name: github-to-sheets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  issues:
    types: [opened, deleted, transferred, closed, reopened, assigned, unassigned, labeled, unlabeled]

jobs:
    github-to-sheets:
        runs-on: ubuntu-latest
        name: github-to-sheets
        steps:
        - name: github-to-sheets
          id: github-to-sheets
          uses: rzykie/github-to-sheets
          with:
            google-api-service-account-credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_DATA }}
            document-id: '1uJoQN11JIdzgz8RhBVN3affHOX9gx-gO'
            sheet-name: 'Sheet1'
